### ISSUE TITLE
RMF slows simulations dramatically even at low output rate

### ISSUE THREAD

**Issue by barakr** [salilab/npctransport#8] opened 2013-08-06 20:12 UTC
Adding RMF output slows down the simulation dramatically. This probably also relates to the terrible chimera slowness? Here is an example to reproduce this. Results do not depend on RMF file name that I use (a.rmf or a.rmf2 or a.rmfa). The output rate is pretty slow - once in a few thousand frames, so I don't think it is it.

No RMF = quick:
$  imp ~/imp_git/fast/module_bin/npctransport/fg_simulation --configuration modules/npctransport/projects/NPC_Anchored/Cfg/NPC2007_new_slack15.cfg --conformations '' --short_init_factor 0.01

With RMF = terribly slow:
$  imp ~/imp_git/fast/module_bin/npctransport/fg_simulation --configuration modules/npctransport/projects/NPC_Anchored/Cfg/NPC2007_new_slack15.cfg --conformations 'a.rmf' --short_init_factor 0.01

**Comment by benmwebb** [comment] 2021-08-13 17:07
Cannot reproduce with current head, so closing for now.

**Closed by benmwebb** 2021-08-13 17:07 UTC
